cf-utils: src/cf-utils.c File Reference
cf-utils.c File Reference
#include "cf-utils.h"
Functions
static bool is_vowel (char a)
static bool is_consonant (char a)
static void get_vowel (const char *text, char *vow, int i, int *k)
static void get_vowels (const char *text, char *vow)
static void get_consonant (const char *text, char *cons, int i, int *k)
static void get_consonants (const char *text, char *cons)
static bool all_consonants (char *string)
static bool all_vowels (char *string)
static bool char_in_text (const char *text, char a)
static bool string_in_text (const char *text, char *string)
void cons_vow (const char *text, char *cons, char *vow)
Variables
static const char EOS = '\0'
static const int ZERO = 0
static const char U = 'U'
static const char O = 'O'
static const char I = 'I'
static const char E = 'E'
static const char A = 'A'
Function Documentation
all_consonants()
static bool all_consonants (char * string) static
Definition at line 51 of file cf-utils.c.
References is_consonant(), and ZERO.
Referenced by cons_vow().
all_vowels()
static bool all_vowels (char * string) static
Definition at line 59 of file cf-utils.c.
References is_vowel(), and ZERO.
Referenced by cons_vow().
char_in_text()
static bool char_in_text (const char * text, char a) static
Definition at line 66 of file cf-utils.c.
References ZERO.
Referenced by string_in_text().
cons_vow()
void cons_vow (const char * text, char * cons, char * vow)
Estrae le consonanti e le vocali da una stringa di caratteri. La procedura popola due array (parametri di output) secondo questo criterio: nell'array cons sono inserite tutte le consonanti di text (nell'ordine in cui compaiono), mentre in vow sono inserite tutte le vocali di text (nell'ordine in cui compaiono).
Warning
Il case delle lettere deve essere rispettato.
I caratteri non afabetici devono essere ignorati.
La lettera 'Y' o 'y' è considerata consonante.
tutti i parametri sono stringhe.
Parameters
[in] text la stringa da suddividere
[out] cons la sequenza di consonanti
[out] vow la sequenza di vocali
Precondition
nessun parametro deve essere NULL
Postcondition
la lunghezza di str non deve essere inferiore alla somma delle lunghezze di cons e di vow
tutti i caratteri di cons devono essere consonanti
tutti i caratteri di vow devono essere vocali
tutti i caratteri di cons devono occorrere in text
tutti i caratteri di vow devono occorrere in text
Definition at line 80 of file cf-utils.c.
References all_consonants(), all_vowels(), get_consonants(), get_vowels(), and string_in_text().
get_consonant()
static void get_consonant (const char * text, char * cons, int i, int * k) static
Definition at line 39 of file cf-utils.c.
References is_consonant().
Referenced by get_consonants().
get_consonants()
static void get_consonants (const char * text, char * cons) static
Definition at line 44 of file cf-utils.c.
References EOS, get_consonant(), and ZERO.
Referenced by cons_vow().
get_vowel()
static void get_vowel (const char * text, char * vow, int i, int * k) static
Definition at line 27 of file cf-utils.c.
References is_vowel().
Referenced by get_vowels().
get_vowels()
static void get_vowels (const char * text, char * vow) static
Definition at line 32 of file cf-utils.c.
References EOS, get_vowel(), and ZERO.
Referenced by cons_vow().
is_consonant()
static bool is_consonant (char a) static
Definition at line 23 of file cf-utils.c.
References is_vowel().
Referenced by all_consonants(), and get_consonant().
is_vowel()
static bool is_vowel (char a) static
Definition at line 18 of file cf-utils.c.
References A, E, I, O, and U.
Referenced by all_vowels(), get_vowel(), and is_consonant().
string_in_text()
static bool string_in_text (const char * text, char * string) static
Definition at line 73 of file cf-utils.c.
References char_in_text(), and ZERO.
Referenced by cons_vow().
Variable Documentation
A
const char A = 'A' static
Definition at line 16 of file cf-utils.c.
Referenced by is_vowel().
E
const char E = 'E' static
Definition at line 15 of file cf-utils.c.
Referenced by is_vowel().
EOS
const char EOS = '\0' static
Definition at line 10 of file cf-utils.c.
Referenced by get_consonants(), and get_vowels().
I
const char I = 'I' static
Definition at line 14 of file cf-utils.c.
Referenced by is_vowel().
O
const char O = 'O' static
Definition at line 13 of file cf-utils.c.
Referenced by is_vowel().
U
const char U = 'U' static
Definition at line 12 of file cf-utils.c.
Referenced by is_vowel().
ZERO
const int ZERO = 0 static
Definition at line 11 of file cf-utils.c.
Referenced by all_consonants(), all_vowels(), char_in_text(), get_consonants(), get_vowels(), and string_in_text().