cf-utils: src/cf-utils.h File Reference
cf-utils.h File Reference
#include <assert.h>
#include <ctype.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
Functions
void cons_vow (const char *text, char *cons, char *vow)
Function Documentation
cons_vow()
void cons_vow (const char * text, char * cons, char * vow)
Estrae le consonanti e le vocali da una stringa di caratteri. La procedura popola due array (parametri di output) secondo questo criterio: nell'array cons sono inserite tutte le consonanti di text (nell'ordine in cui compaiono), mentre in vow sono inserite tutte le vocali di text (nell'ordine in cui compaiono).
Warning
Il case delle lettere deve essere rispettato.
I caratteri non afabetici devono essere ignorati.
La lettera 'Y' o 'y' è considerata consonante.
tutti i parametri sono stringhe.
Parameters
[in] text la stringa da suddividere
[out] cons la sequenza di consonanti
[out] vow la sequenza di vocali
Precondition
nessun parametro deve essere NULL
Postcondition
la lunghezza di str non deve essere inferiore alla somma delle lunghezze di cons e di vow
tutti i caratteri di cons devono essere consonanti
tutti i caratteri di vow devono essere vocali
tutti i caratteri di cons devono occorrere in text
tutti i caratteri di vow devono occorrere in text
Definition at line 80 of file cf-utils.c.
References all_consonants(), all_vowels(), get_consonants(), get_vowels(), and string_in_text().